### ISSUE TITLE
Some issues encountered when using FishFuzz.

### ISSUE THREAD

**Issue by blu3sh0rk** [HexHive/FishFuzz#2]
Hi，

I have encountered three issues when using FishFuzz:

1. Is it possible to upload the image to Dockerhub? When using the Dockerfile to build a Docker image, `LLVM-14` is automatically installed in the container according to the system suggestion(This situation may occur occasionally). Therefore, I chose to manually install the dependencies in an empty Ubuntu 20.04 container, which is a bit more complex but can also solve the problem.

2. I encountered the following issues when using Examples For Wrapper Usage.

```
mkdir -p /benchmark/source/ && cd /benchmark/source/
wget https://mujs.com/downloads/mujs-1.0.2.tar.gz && tar xzf mujs-1.0.2.tar.gz -C /benchmark

export FF_DRIVER_NAME=mujs
export CC=/FishFuzz/ff-all-in-one
export CXX=/FishFuzz/ff-all-in-one++
export CFLAGS="-fsanitize=address"
export CXXFLAGS="-fsanitize=address"

cd /benchmark/mujs-1.0.2 && make -j$(nproc)
```

The issues I encountered and my approach to solving them.

```
/usr/bin/ld: /tmp/mujs-1add47.o: in function jsR_hasproperty': ld-temp.o:(.text.jsR_hasproperty[jsR_hasproperty$21576b91ab9b15712202e1b4a494877f]+0xd0a): undefined reference to __ubsan_handle_pointer_overflow'
/usr/bin/ld: ld-temp.o:(.text.jsR_hasproperty[jsR_hasproperty$21576b91ab9b15712202e1b4a494877f]+0xe75): undefined reference to `__ubsan_handle_type_mismatch_v1'
```

I changed the compilation flags:

```
export CFLAGS="-fsanitize=undefined" LDFLAGS="-fsanitize=undefined -lubsan"
```

3. I encountered the following issues when using Examples For Manual Compilation.

My compilation command is (I modified some path variables):

```
export FF_DRIVER_NAME=mujs
export SRC_DIR=/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2
export FUZZER=FishFuzz
export FUZZ_DIR=/home/lzy/fuzz/FishFuzz/FF_AFL++/fuzz/$FF_DRIVER_NAME/$FUZZER/$FF_DRIVER_NAME

# step 1, generating .bc file, you can use wllvm or similar approach as you wish
export CC="clang -fsanitize=address -flto -fuse-ld=gold -Wl,-plugin-opt=save-temps -Wno-unused-command-line-argument"
export CXX="clang++ -fsanitize=address -flto -fuse-ld=gold -Wl,-plugin-opt=save-temps -Wno-unused-command-line-argument"
cd $SRC_DIR && make -j$(nproc)

# step 2, coverage instrumentation and analysis
export PREFUZZ=/home/lzy/fuzz/FishFuzz/FF_AFL++
export TMP_DIR=$PWD/TEMP
export ADDITIONAL_COV="-load $PREFUZZ/afl-llvm-pass.so -test -outdir=$TMP_DIR -pmode=conly"
export ADDITIONAL_ANALYSIS="-load $PREFUZZ/afl-llvm-pass.so -test -outdir=$TMP_DIR -pmode=aonly"
export BC_PATH=$(find . -name "$FF_DRIVER_NAME.0.5.precodegen.bc" -printf "%h\n")/
mkdir -p $TMP_DIR
opt $ADDITIONAL_COV $BC_PATH$FF_DRIVER_NAME.0.5.precodegen.bc -o $BC_PATH$FF_DRIVER_NAME.final.bc
```

And

```
$ opt $ADDITIONAL_COV $BC_PATH$FF_DRIVER_NAME.0.5.precodegen.bc -o $BC_PATH$FF_DRIVER_NAME.final.bc
opt: Unknown command line argument '-test'.  Try: 'opt --help'
opt: Did you mean '--tti'?
opt: for the -o option: may not occur within a group!
opt: Unknown command line argument '-outdir=/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP'.  Try: 'opt --help'
opt: Did you mean '-o'?
opt: Unknown command line argument '-pmode=conly'.  Try: 'opt --help'
opt: Did you mean '--o=conly'?
```

May I know where the configuration went wrong? Thank you.

**Comment by blu3sh0rk** [comment]
The third point is about using `afl-fish-pass.so` in FF_AFL++ to enable LLVM passes instead of `afl-llvm-pass.so`. However, when running the command `$CC $ADDITIONAL_FUNC $BC_PATH$FF_DRIVER_NAME.final.bc -o $FF_DRIVER_NAME.fuzz $EXTRA_LDFLAGS $ASAN_LIBS`, the following issue occurred：
```
Trying to initialized callgraph...
['/home/lzy/fuzz/FishFuzz/FF_AFL++/dyncfg/dis_calc', '-t', '/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP', '-m', 'cg', '-d', '/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP/dot-files/callgraph.dot', '-o', '/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP/runtimes/callgraph.dot', '-a', '/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP/runtimes/callmap.json']
Failed execute cg /home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP/dot-files/callgraph.dot!
```

**Comment by kdsjZh** [comment]
Hi blu3sh0rk,

Thanks for the report.

Regarding your first question, when I build using `docker build -t $DOCKER_NAME  $PATH_TO_DOCKER`, I didn't find any suggestion for llvm14. Given that FishFuzz is still in development (to fit the fuzzbench), I'll upload the image when FishFuzz can work with fuzzbench and maybe you could use the dockerfile first?

Regarding the second question:

### Why the ubsan will be used in compiling but not linking
FishFuzz try to detect if there are any sanitizer, if no sanitizer are used, FishFuzz will automatically include UBSan to make sure FishFuzz can have direction. In your case, FishFuzz didn't find any sanitizer in it's compilation and include the UBSan. But didn't link with -lubsan in linking stage.

### I've already included ASan in CFLAGS?
Yes, but in mujs, the CFLAGS environment are not imported in makefile

### What should I do to play with mujs?
In theory this is an bug, I didn't consider this case, but currently, I don't have too much time to fix it. It will be added to my todo list. Now the simplist way is merge CC with CFLAGS, aka `export CC="$CC -fsanitize=address"`. In that case the mujs can work. The wrapper also should work in other programs.

**Comment by kdsjZh** [comment]
regarding your 3rd issue, I could not reproduce, could you try that again and check if `$FISHFUZZ/FF_AFL/dyncfg/dis_calc` binary exists and executable?

Please let me know if these answers fail to address your questions or you find other bugs

**Comment by blu3sh0rk** [comment]
In FF_AFL, I was able to complete the entire manual compilation process, so I found that FF_AFL++ is missing the output file `funcid.csv` when compared.

```
FF_AFL
root@7cb57acd666e:/home/lzy/fuzz/FishFuzz/FF_AFL/benchmark/mujs-1.0.2/TEMP# ls
bug_cmps.csv  callmap.csv  cmp_log.csv  dbg_bug.csv  dot-files  firstbb.csv  funcid.csv  funcmap.csv  locmap.csv  paired_edges.csv  runtimes  vulnfunc.csv

FF_AFL++
root@aa12fc62b87d:/home/lzy/fuzz/FishFuzz/FF_AFL++/benchmark/mujs-1.0.2/TEMP# ls 
bug_cmps.csv  callmap.csv  cmp_log.csv  dbg_bug.csv  dot-files  firstbb.csv  funcmap.csv  paired_edges.csv  runtimes  vulnfunc.csv
```
Therefore, when executing the command `$PREFUZZ/scripts/gen_initial_distance.py $TMP_DIR` and attempting to initialize the callgraph, it failed. Could you please identify which step caused the issue? As `funcid.csv` was not generated, I have configured other aspects temporarily. Thank you for your response!
```
$file /home/lzy/fuzz/FishFuzz/FF_AFL/dyncfg/dis_calc
/home/lzy/fuzz/FishFuzz/FF_AFL/dyncfg/dis_calc: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=435d51fd46eee1dee1a9c010968d5754c388c9ea, for GNU/Linux 3.2.0, not stripped
```

**Comment by kdsjZh** [comment]
Sorry, Regarding the FF_AFL++, the compile command is a bit different, this is something I forgot to include in the manual, could you refer to the demo in artifact evaluation [scripts](https://github.com/HexHive/FishFuzz/blob/master/paper/artifact/two-stage/build/cflow.sh )?

**Comment by kdsjZh** [comment]
BTW, does the FF_AFL and FF_AFL++'s wrapper work correctly now? I try to validate the wrapper and at least it works in my env.

**Comment by blu3sh0rk** [comment]
> 
The script compiled successfully with the modifications you suggested, except for the ASAN_LIBS environment variable, which required some adjustments because：
```
$find `llvm-config --libdir` -name libclang_rt.asan-*.a
/usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.asan-i386.a
/usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.asan-preinit-x86_64.a
/usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.asan-preinit-i386.a
/usr/lib/llvm-12/lib/clang/12.0.1/lib/linux/libclang_rt.asan-x86_64.a
```
I change it to 
```
export ASAN_LIBS=$(find `llvm-config --libdir` -name libclang_rt.asan-*.a | grep -Ev "preinit|i386")
```

By the way,`ff-all-in-one` and `ff-all-in-one` work correctly.

Thank you!
