### ISSUE TITLE
potential target miss in instrumentation?

### ISSUE THREAD

**Issue by 1ncande5cence** [HexHive/FishFuzz#5]
Dear authors,
I get confused when performing the target instrumentation.

In `FishFuzz/FF_AFL/llvm_mode/afl-llvm-pass.so.cc`
Here is the code snippet
```  
        if (is_coverage){
               ...
               cur_loc = AFL_R(MAP_SIZE);
               ...        
         }

        if (is_analysis) {

          u32 id = (is_coverage) ? cur_loc : get_block_id(BB);      ----> line a
          std::string filename = F.getParent()->getSourceFileName();
          std::size_t found = filename.find_last_of("/\\");
          if (found != std::string::npos)
          filename = filename.substr(found + 1);

          std::string bb_name = filename + ":" + F.getName().str() + ":" + std::to_string(id);
          
         ...

          if (bb_name.empty() || !id) {    ----> line b
            empty_blocks ++;
            continue;
          }
          ...
          bool has_san_label = has_sanitizer_instrumentation(BB);   ----> line c
          ...
```

First in pmode=conly mode, goto first if condition, `cur_loc` is instrumented in the bc file, which can be `0` (random()%MAP_SIZE).
Next in pmode=aonly mode, goto second if condition, however, `id` can be `0` (get_block_id(BB)) at line a, which will pass line b  and not goto line c and find the sanitizer instrumentation.

Will this lead to a potential target miss? For example, I have a block and the block id happens to be 0, and we will miss the sanitizer instrumentation inside this block?

Thank you for your help!

**Comment by kdsjZh** [comment]
Hi,

Thanks for the code review and report. Yes, this issue can happen and lead to potentially missing targets. I fix this issue by replacing `AFL_R(MAP_SIZE)` to `AFL_R(MAP_SIZE - 1) + 1`.

However, in practice, the ratio of missing a target is 1/MAP_SIZE. As claimed in the paper, FishFuzz targets up to hundred thousands of targets. Therefore, missing <10 targets would not introduce significant differences. 

Anyway, thanks again for the report! Feel free to reopen it if it fail to address the issue.
